name: "A Dog's Life"
favicon: null
layout_spectrum: 0.6125432255212218
typography_spectrum: 0.8899543753359467
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.2931619780138135
  lightness: 0.012007663492113352
  saturation: 0.23729086061939597
  rhythmicContrast: 0.9930840358138084
purpose: []
